export const errros = {
  '10': 'ZERO_SETTINGS_EXCEEDED',
  '11': 'ZERO_SETTINGS_NOT_REACHED',
  '12': 'MAX_LOAD_EXCEEDED',
  '13': 'MIN_LOAD_NOT_REACHED',
  '14': 'MEASURE_TOO_LONG',
  '15': 'MEASURE_TOO_SHORT',
  '16': 'WEIGHT_NOT_STABLE',
  '17': 'ANGLE_EXCEEDED',
};
